name: Add the name of your quickstart
authors:
    - Samuel V.
    - Stijn P.
# Optionally you can add additional sources as some won't be auto detected by the scripts.
# You can also redirect to external webpages when the dashboards provides specific installation instructions
sources:
  - Kubernetes
  - Prometheus
  - name: CoreDNS
    url: https://github.com/coredns/coredns/tree/master/plugin/metrics
